# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate test file
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_and_save_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          wget https://google.github.io/styleguide/pylintrc
          pylint --rcfile pylintrc --disable=W0703,R1734,R1735,C0209,C0103,R1732 src/gcp_scanner/*.py
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new branch
        run: |
          git checkout -b new-branch
      - name: Run Python script and generate output file
        run: |
          python test/generate_file.py > test/output.txt
      - name: Commit output file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add output.txt"
          file_pattern: "test/output.txt"
      - name: Push changes to new-branch branch
        run: |
          git config user.name "smallChenn"
          git config user.email "chenbingjie1998@gmail.com"
          git merge origin/new-branch
          git push origin new-branch
